--------------------------------------------------------
--  Fichier créé - vendredi-juin-21-2024   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "FARES1"."CLIENT" 
   (	"ID_CLIENT" NUMBER(*,0), 
	"PRENOM" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"TELEPHONE" VARCHAR2(8 BYTE), 
	"NB_RECLAMATION" NUMBER(*,0), 
	"NB_BONUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "FARES1"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"NOM" VARCHAR2(200 BYTE), 
	"PRENOM" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"MDP" VARCHAR2(8 BYTE), 
	"DATEE" DATE, 
	"SALAIRE" NUMBER(*,0), 
	"ROLEE" VARCHAR2(200 BYTE), 
	"GENREE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GERER
--------------------------------------------------------

  CREATE TABLE "FARES1"."GERER" 
   (	"ID_EMPLOYE" NUMBER(*,0), 
	"ID_VOITURE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "FARES1"."MAINTENANCE" 
   (	"ID_MAINTENANCE" NUMBER(*,0), 
	"DATE_HR" TIMESTAMP (6), 
	"TYPE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"COUT" VARCHAR2(100 BYTE), 
	"DUREE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFILE
--------------------------------------------------------

  CREATE TABLE "FARES1"."PROFILE" 
   (	"COD_UG" VARCHAR2(20 BYTE), 
	"COD_PRF" VARCHAR2(20 BYTE), 
	"NUM_PRF" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"COL_1" VARCHAR2(20 BYTE), 
	"COL_2" VARCHAR2(20 BYTE), 
	"COL_3" VARCHAR2(20 BYTE), 
	"CODE_USER" VARCHAR2(20 BYTE), 
	"COD_TIT_PRF" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SESSION
--------------------------------------------------------

  CREATE TABLE "FARES1"."SESSION" 
   (	"ID_SESSION" NUMBER(*,0), 
	"MODEE" VARCHAR2(50 BYTE), 
	"NIV_BATTERIE" VARCHAR2(100 BYTE), 
	"VITESSE" NUMBER(*,0), 
	"HAPPY_HOUR" VARCHAR2(100 BYTE), 
	"PRIX" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TEMPORARY_TABLE
--------------------------------------------------------

  CREATE TABLE "FARES1"."TEMPORARY_TABLE" 
   (	"COD_UG" VARCHAR2(20 BYTE), 
	"COD_PRF" VARCHAR2(20 BYTE), 
	"NUM_PRF" VARCHAR2(20 BYTE), 
	"DATE_DEBUT" DATE, 
	"DATE_FIN" DATE, 
	"COL_1" VARCHAR2(20 BYTE), 
	"COL_2" VARCHAR2(20 BYTE), 
	"COL_3" VARCHAR2(20 BYTE), 
	"CODE_USER" VARCHAR2(20 BYTE), 
	"COD_TIT_PRF" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VOITURE
--------------------------------------------------------

  CREATE TABLE "FARES1"."VOITURE" 
   (	"ID_VOITURE" NUMBER(*,0), 
	"ID_CLIENT" NUMBER(*,0), 
	"ID_MAINTENANCE" NUMBER(*,0), 
	"MATRICULE" VARCHAR2(100 BYTE), 
	"BATTERIE_LVL" VARCHAR2(200 BYTE), 
	"BATTERIE_CAP" VARCHAR2(100 BYTE), 
	"MODEL" VARCHAR2(100 BYTE), 
	"ETAT" VARCHAR2(100 BYTE), 
	"QUNATITE" NUMBER(*,0), 
	"ID_SESSION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FARES1.CLIENT
SET DEFINE OFF;
REM INSERTING into FARES1.EMPLOYE
SET DEFINE OFF;
REM INSERTING into FARES1.GERER
SET DEFINE OFF;
REM INSERTING into FARES1.MAINTENANCE
SET DEFINE OFF;
REM INSERTING into FARES1.PROFILE
SET DEFINE OFF;
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','ADMIN_GRH','009',to_date('12/05/24','DD/MM/RR'),to_date('12/05/26','DD/MM/RR'),null,null,null,'E0022','01');
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','ADMIN_GRH','02',to_date('01/06/24','DD/MM/RR'),to_date('23/11/24','DD/MM/RR'),null,null,null,'E0019','02');
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_IT','03',to_date('01/06/24','DD/MM/RR'),null,null,null,null,'E0013','04');
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','RSI','01',to_date('13/10/24','DD/MM/RR'),null,null,null,null,'E0022','03');
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','RSI','03',to_date('03/12/24','DD/MM/RR'),to_date('23/11/24','DD/MM/RR'),null,null,null,'E0013','02');
Insert into FARES1.PROFILE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_IT','01',to_date('01/06/24','DD/MM/RR'),to_date('09/06/24','DD/MM/RR'),null,null,null,'E0022','04');
REM INSERTING into FARES1."SESSION"
SET DEFINE OFF;
REM INSERTING into FARES1.TEMPORARY_TABLE
SET DEFINE OFF;
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','ADMIN_GRH','009',to_date('12/05/24','DD/MM/RR'),to_date('12/05/26','DD/MM/RR'),null,null,null,'E0022','01');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','ADMIN_GRH','02',to_date('01/06/24','DD/MM/RR'),to_date('23/11/24','DD/MM/RR'),null,null,null,'E0019','02');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_IT','03',to_date('01/06/24','DD/MM/RR'),null,null,null,null,'E0013','04');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','RSI','03',to_date('03/12/24','DD/MM/RR'),to_date('23/11/24','DD/MM/RR'),null,null,null,'E0013','02');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_IT','01',to_date('16/06/24','DD/MM/RR'),null,null,null,null,'E0022','03');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_RH','01',to_date('01/06/24','DD/MM/RR'),to_date('09/06/24','DD/MM/RR'),null,null,null,'E0022','04');
Insert into FARES1.TEMPORARY_TABLE (COD_UG,COD_PRF,NUM_PRF,DATE_DEBUT,DATE_FIN,COL_1,COL_2,COL_3,CODE_USER,COD_TIT_PRF) values ('300','GST_IT','01',to_date('01/06/24','DD/MM/RR'),to_date('09/06/24','DD/MM/RR'),null,null,null,'E0022','04');
REM INSERTING into FARES1.VOITURE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PK_CLIENT" ON "FARES1"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PK_EMPLOYE" ON "FARES1"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index GERER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."GERER_PK" ON "FARES1"."GERER" ("ID_EMPLOYE", "ID_VOITURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MAINTENANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PK_MAINTENANCE" ON "FARES1"."MAINTENANCE" ("ID_MAINTENANCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFILE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PROFILE_PK" ON "FARES1"."PROFILE" ("COD_UG", "COD_PRF", "NUM_PRF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SESSION
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PK_SESSION" ON "FARES1"."SESSION" ("ID_SESSION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_VOITURE
--------------------------------------------------------

  CREATE UNIQUE INDEX "FARES1"."PK_VOITURE" ON "FARES1"."VOITURE" ("ID_VOITURE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "FARES1"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("NB_RECLAMATION" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" MODIFY ("NB_BONUS" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("DATEE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" MODIFY ("ROLEE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "FARES1"."GERER" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."GERER" MODIFY ("ID_VOITURE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."GERER" ADD CONSTRAINT "GERER_PK" PRIMARY KEY ("ID_EMPLOYE", "ID_VOITURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "FARES1"."MAINTENANCE" MODIFY ("ID_MAINTENANCE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."MAINTENANCE" MODIFY ("DATE_HR" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."MAINTENANCE" ADD CONSTRAINT "PK_MAINTENANCE" PRIMARY KEY ("ID_MAINTENANCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFILE
--------------------------------------------------------

  ALTER TABLE "FARES1"."PROFILE" ADD CONSTRAINT "PROFILE_PK" PRIMARY KEY ("COD_UG", "COD_PRF", "NUM_PRF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARES1"."PROFILE" MODIFY ("CODE_USER" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."PROFILE" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."PROFILE" MODIFY ("NUM_PRF" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."PROFILE" MODIFY ("COD_PRF" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."PROFILE" MODIFY ("COD_UG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SESSION
--------------------------------------------------------

  ALTER TABLE "FARES1"."SESSION" MODIFY ("ID_SESSION" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" MODIFY ("MODEE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" MODIFY ("NIV_BATTERIE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" MODIFY ("VITESSE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" MODIFY ("HAPPY_HOUR" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."SESSION" ADD CONSTRAINT "PK_SESSION" PRIMARY KEY ("ID_SESSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEMPORARY_TABLE
--------------------------------------------------------

  ALTER TABLE "FARES1"."TEMPORARY_TABLE" MODIFY ("CODE_USER" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."TEMPORARY_TABLE" MODIFY ("DATE_DEBUT" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."TEMPORARY_TABLE" MODIFY ("NUM_PRF" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."TEMPORARY_TABLE" MODIFY ("COD_PRF" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."TEMPORARY_TABLE" MODIFY ("COD_UG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "FARES1"."VOITURE" MODIFY ("ID_VOITURE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("ID_MAINTENANCE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("MATRICULE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("BATTERIE_LVL" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("BATTERIE_CAP" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("MODEL" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("QUNATITE" NOT NULL ENABLE);
  ALTER TABLE "FARES1"."VOITURE" ADD CONSTRAINT "PK_VOITURE" PRIMARY KEY ("ID_VOITURE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FARES1"."VOITURE" MODIFY ("ID_SESSION" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GERER
--------------------------------------------------------

  ALTER TABLE "FARES1"."GERER" ADD CONSTRAINT "ID_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "FARES1"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "FARES1"."GERER" ADD CONSTRAINT "ID_VOITURE" FOREIGN KEY ("ID_VOITURE")
	  REFERENCES "FARES1"."VOITURE" ("ID_VOITURE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VOITURE
--------------------------------------------------------

  ALTER TABLE "FARES1"."VOITURE" ADD CONSTRAINT "FK_VOITURE_CHARGER_SESSION" FOREIGN KEY ("ID_SESSION")
	  REFERENCES "FARES1"."SESSION" ("ID_SESSION") ENABLE;
  ALTER TABLE "FARES1"."VOITURE" ADD CONSTRAINT "ID_CLIENT" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "FARES1"."CLIENT" ("ID_CLIENT") ENABLE;
  ALTER TABLE "FARES1"."VOITURE" ADD CONSTRAINT "ID_MAINTENANCE" FOREIGN KEY ("ID_MAINTENANCE")
	  REFERENCES "FARES1"."MAINTENANCE" ("ID_MAINTENANCE") ENABLE;
